#!/usr/bin/python3
from optparse import OptionParser
from collections import deque
from typing import Optional, List
import random
import sys

def mask_logical_addr(addr: int):
    return (addr >> 8), (addr & 0xff)

# def get_byte_referenced(frame: bytes, offset: int):
#     byte_referenced = -(256-frame[offset]) if frame[offset] >= 128 else frame[offset]
#     return byte_referenced

def read_physical_memory(frame_num: int, frame_size=256):
    with open("BACKING_STORE.bin", "rb") as file:
        file.seek(frame_size*frame_num)
        return file.read(frame_size)
    
class Page:
    def __init__(self, page_number: int, frame: bytes):
        self.page_number = page_number
        self.frame = frame

class FIFOCache:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.cache = {}
        self.queue = deque()

    def get(self, key: int) -> Optional[Page]:
        if key in self.cache:
            self.queue.remove(key)
            self.queue.append(key)
            return self.cache[key]
        else:
            return None

    def put(self, key: int, value: Page):
        if key in self.cache:
            self.queue.remove(key)
        elif len(self.cache) == self.capacity:
            oldest = self.queue.popleft()
            del self.cache[oldest]
        self.cache[key] = value
        self.queue.append(key)

class RDCache:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.cache = {}
        self.queue = [] 
        
    def get(self, key) -> Optional[Page]:
        if key in self.cache:
            self.queue.remove(key)
            self.queue.append(key)
            return self.cache[key]
        else:
            return None
    
    def put(self, key, value):
        if key in self.cache:
            self.queue.remove(key)
        elif len(self.cache) == self.capacity:
            ranNum = random.randint(0, self.capacity-1)
            old = self.queue.pop(ranNum)
            del self.cache[old]
        self.cache[key] = value
        self.queue.append(key)

class LRUCache:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.cache = {}
        self.queue = []

    def get(self, key) -> Optional[Page]:
        if key in self.cache:
            self.queue.remove(key)
            self.queue.append(key)
            return self.cache[key]
        else:
            return None
    
    def put(self, key, value):
        if len(self.cache) == self.capacity and key not in self.cache:
            evicted_key = self.queue.pop(0)
            del self.cache[evicted_key]
        self.cache[key] = value
        if key in self.queue:
            self.queue.remove(key)
        self.queue.append(key)

class OPTCache:
    def __init__(self, capacity: int, future_accesses: List[int]):
        self.capacity = capacity
        self.cache = {}
        self.future_accesses = future_accesses
        
    def get(self, key) -> Optional[Page]:
        if key in self.cache:
            self.future_accesses.pop(0)
            return self.cache[key]
        else:
            return None
        
    def put(self, key, value):
        self.future_accesses.pop(0)
        if len(self.cache) == self.capacity:
            least_significant = self.find_replacement()
            del self.cache[least_significant]
        self.cache[key] = value
    
    def find_replacement(self):
        temp = {}
        for key in self.cache:
            try:
                index = self.future_accesses.index(key)
            except ValueError:
                index = float("inf")
            temp[key] = index
        return sorted(temp, reverse=True)[0]

class VirtualMemory:
    def __init__(self, pra: str, frames: int, future_accesses: List[int]):
        self.frames = frames
        self.lookups = 0
        
        self.tlb = FIFOCache(16)
        self.tlb_hits = 0
        self.tlb_misses = 0
        self.tlb_lookups = 0
        
        if pra == "FIFO":
            self.page_table = FIFOCache(frames)
        elif pra == "LRU":
            self.page_table = LRUCache(frames)
        elif pra == "OPT":
            self.page_table = OPTCache(frames, future_accesses)
        elif pra == "RD":
            self.page_table = RDCache(frames)
        
        self.page_faults = 0
        self.page_lookups = 0
        self.page_number = -1
    
    def translate_virtual_addr(self, logical_addr: int):
        self.lookups += 1
        page_number, offset = mask_logical_addr(logical_addr)
        page = self.page_table_lookup(page_number)
        byte_referenced = -(256-page.frame[offset]) if page.frame[offset] >= 128 else page.frame[offset]
        self.print_addr(logical_addr, byte_referenced, page.page_number, page.frame)
        
    def tlb_lookup(self, page_number: int):
        self.tlb_lookups += 1
        page = self.tlb.get(page_number)
        if page:
            self.tlb_hits += 1
        else:
            self.tlb_misses +=1
        return page

    def page_table_lookup(self, page_number: int):
        self.page_lookups += 1
        
        page = self.tlb_lookup(page_number)
        if not page:
            page = self.page_table.get(page_number)
            if not page:
                self.page_number += 1
                self.page_faults += 1
                frame = read_physical_memory(page_number)
                page = Page(self.page_number, frame)
                self.tlb.put(self.page_number, page)
                self.page_table.put(self.page_number, page)
        return page
    
    def print_addr(self, addr: int, value: int, frame_number: int, entire_frame: bytes):
        print(f"{addr}, {value}, {frame_number}, {bytes.hex(entire_frame).upper()}")
    
    def print_stat(self):
        print(f"Number of Translated Addresses = {self.lookups}")
        print(f"Page Faults = {self.page_faults}")
        print("Page Fault Rate = {:3.3f}".format(self.page_faults/self.page_lookups))
        print(f"TLB Hits = {self.tlb_hits}")
        print(f"TLB Misses = {self.tlb_misses}")
        print("TLB Hit Rate = {:3.3f}".format(self.tlb_hits/self.tlb_lookups))

def main():
    parser = OptionParser()
    parser.add_option("-f","--frames", default=256, help="memSim frames to use: an integer <= 256 and > 0", action="store", type="int", dest="frames")
    parser.add_option("-p","--PRA", default="FIFO", help="memSim page replacement algorithms to use: FIFO, LRU, OPT, RD", action="store", type="string", dest="pra")
    (option, args) = parser.parse_args()
    if not len(args):
        print("No Input Detected")
        return
    
    frames = option.frames
    frames = 256 if frames < 0 or frames > 256 else frames
    
    pra = option.pra
    pra = "FIFO" if pra not in ["FIFO", "OPT", "LRU", "RD"] else pra
    
    try:
        with open(args[0], "r") as in_file:
            virtual_addresses = in_file.read().split()
            virtual_addresses = [int(addr) for addr in virtual_addresses]
        future_accesses = [mask_logical_addr(addr)[0] for addr in virtual_addresses]
        vm = VirtualMemory(option.pra, option.frames, future_accesses)
        for addr in virtual_addresses:
            vm.translate_virtual_addr(addr)
        vm.print_stat()
    except FileNotFoundError:
        print("Incorrect <reference-sequence-file.txt> Detected")
        return
    

if __name__ == '__main__':
    main()
    